# IRIS 데이타 셋 

* 앤더슨  
* 단어 : sepal(꽃받침), petal(꽃잎)
* 데이터구조 csv file
 * 폭, 길이 : s-L, s-W, p-L, p-W
 * 색깔 3종류 :  씨토우싸 setosa, 버시컬러 versicolor, 브제니카 virginica



# 데이타 불러오기

In [14]:
from IPython.display import HTML
HTML('<iframe src=http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data width=300 height=200></iframe>')

* observation : 150개 
* features : 4개
* response : iris 종류

In [8]:
from sklearn.datasets import load_iris
iris = load_iris()
print iris.feature_names


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


# iris 데이타 구조 살펴보기 

In [21]:
# iris 데이타 구조 살펴보기 
print type(iris) #<class 'sklearn.datasets.base.Bunch'>

# Bunch 클래스
help(iris)

<class 'sklearn.datasets.base.Bunch'>
Help on Bunch in module sklearn.datasets.base object:

class Bunch(__builtin__.dict)
 |  Container object for datasets
 |  
 |  Dictionary-like object that exposes its keys as attributes.
 |  
 |  >>> b = Bunch(a=1, b=2)
 |  >>> b['b']
 |  2
 |  >>> b.b
 |  2
 |  >>> b.a = 3
 |  >>> b['a']
 |  3
 |  >>> b.c = 6
 |  >>> b['c']
 |  6
 |  
 |  Method resolution order:
 |      Bunch
 |      __builtin__.dict
 |      __builtin__.object
 |  
 |  Methods defined here:
 |  
 |  __dir__(self)
 |  
 |  __getattr__(self, key)
 |  
 |  __init__(self, **kwargs)
 |  
 |  __setattr__(self, key, value)
 |  
 |  __setstate__(self, state)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ---------------------------------------------------------

In [24]:
# data, target, feature_names 
# (1) data, data.shape
print iris.data
print type(iris.data)#<type 'numpy.ndarray'>


[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [25]:
# (2) target : 0 씨토사, 1 버시컬러, 2  브제니카 
print iris.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [26]:
#(3) feature_names
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [27]:
#feature (X) vs rsponse (Y)  

print iris.data.shape
print iris.target.shape

(150, 4)
(150,)


In [37]:
X = iris.data
y = iris.target



# KNN (K-nearest neighbors) classification

1. K 선정
2. K개 observation 조사
3.

### 1단계 : 

In [29]:
from sklearn.neighbors import KNeighborsClassifier

### 2단계 :  instantiate 
    

In [31]:
knn = KNeighborsClassifier(n_neighbors=1)

In [32]:
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


### 3단계 : 모델 트레이닝
    

In [38]:
knn.fit(X,y)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

### 4단계 : 

In [39]:
knn.predict([3,5,4,2])


/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [35]:
X_new = [[3,5,4,2],[5,4,3,2]]
knn.predict(X_new)

array([2, 1])

# 다른 K 값 사용 

In [36]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x,y)
knn.predict(X_new)

array([1, 1])

# 다른 클래시피케이션 모델 사용

In [42]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X,y)
logreg.predict(X_new)


array([2, 0])

# 뫄들 어봘류에이션
### Model Evaluation


In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target


## Logistic regression



In [3]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X,y)
y_pred = logreg.predict(X)


In [4]:
from sklearn import metrics
print metrics.accuracy_score(y,y_pred)

0.96


# KNN (K=5)


In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
y_pred = knn.predict(X)
print metrics.accuracy_score(y,y_pred)

0.966666666667


# KNN (K=5)


In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X,y)
y_pred = knn.predict(X)
print metrics.accuracy_score(y,y_pred)

1.0


# 트레이닝과 테스틩에서 문제점
*
*
* ㅐ overfit -- 이것은 노이즈 유발


# Evaluation procedure #2 : Train/test split


In [7]:
print X.shape
print y.shape

(150, 4)
(150,)


In [16]:
# step 1 : 분리
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.4, random_state=4)


In [17]:
print X_train.shape
print X_test.shape

(90, 4)
(60, 4)
